"""add hierarchical parent chunks

Revision ID: a4ea3f2e45a6
Revises: f1379da04c93
Create Date: 2026-09-23 10:20:14.209299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4ea3f2e45a6"
down_revision: str | Sequence[str] | None = "f1379da04c93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parent_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id", "parent_index", name="uq_parent_chunks_version_index"
        ),
    )
    op.create_index(
        op.f("ix_parent_chunks_document_version_id"),
        "parent_chunks",
        ["document_version_id"],
        unique=False,
    )
    op.add_column("chunks", sa.Column("parent_chunk_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_chunks_parent_chunk_id"), "chunks", ["parent_chunk_id"], unique=False)
    op.create_foreign_key(
        "fk_chunks_parent_chunk",
        "chunks",
        "parent_chunks",
        ["parent_chunk_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_chunks_parent_chunk",
        "chunks",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_chunks_parent_chunk_id"), table_name="chunks")
    op.drop_column("chunks", "parent_chunk_id")
    op.drop_index(op.f("ix_parent_chunks_document_version_id"), table_name="parent_chunks")
    op.drop_table("parent_chunks")
    # ### end Alembic commands ###
